### ISSUE TITLE
Could you please provide the training code?

### ISSUE THREAD

**Issue by primekangkang** [CIFASIS/wganvo#1]
Hello author, thank you for sharing your code, I am very interested in your work. I read your paper and am very curious about the training details. Could you please provide the training code, because I am a beginner, it will give me great help to go further on this road.  Thank you!

**Comment by jcremona** [comment]
Hello @primekangkang . I updated the README. The main script to train the network is `wgan/wgan_improved.py`. In order to facilitate the installation process, we used Docker containers. It is explained in the README. If you experience any issues with it, just let me know. Thanks!
