### ISSUE TITLE
Cannot create container for service wganvo:

### ISSUE THREAD

**Issue by ggonzalez2022** [CIFASIS/wganvo#5]
Alguna idea ? Any idea ?

make start
docker-compose up -d
Creating network "wganvo-master_default" with the default driver
Creating wganvo-docker ... error

ERROR: for wganvo-docker  Cannot create container for service wganvo: Unknown runtime specified nvidia

ERROR: for wganvo  Cannot create container for service wganvo: Unknown runtime specified nvidia
ERROR: Encountered errors while bringing up the project.
make: *** [Makefile:12: start] Error 1

**Comment by jcremona** [comment]
Hi! Have you checked if nvidia-docker is properly installed?
